// Generated by Copilot
using AIKit.Mcp;
using Microsoft.Extensions.Logging;
using ModelContextProtocol;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using Moq;
using System.Text.Json;
using Xunit;

namespace AIKit.Mcp.Tests;

public class McpCompletionHelpersTests
{
    [Fact]
    public void CreateDictionaryCompletionHandler_ReturnsCompletionHandler()
    {
        // Arrange
        var completions = new Dictionary<string, IEnumerable<string>>
        {
            ["style"] = new[] { "formal", "casual", "technical" }
        };

        // Act
        var handler = McpCompletionHelpers.CreateDictionaryCompletionHandler(completions);

        // Assert
        Assert.NotNull(handler);
    }

    [Fact]
    public void CreateResourceCompletionHandler_ReturnsCompletionHandler()
    {
        // Arrange
        var resourceUris = new[] { "file://doc1.txt", "file://doc2.txt", "file://readme.md" };

        // Act
        var handler = McpCompletionHelpers.CreateResourceCompletionHandler(resourceUris);

        // Assert
        Assert.NotNull(handler);
    }

    [Fact]
    public void CreatePromptCompletionHandler_ReturnsCompletionHandler()
    {
        // Arrange
        var promptNames = new[] { "summarize", "analyze", "translate" };

        // Act
        var handler = McpCompletionHelpers.CreatePromptCompletionHandler(promptNames);

        // Assert
        Assert.NotNull(handler);
    }

    [Fact]
    public void CreateDynamicCompletionHandler_ReturnsCompletionHandler()
    {
        // Arrange
        Func<string, string, IEnumerable<string>> completionFunc = (argName, value) =>
            new[] { $"{argName}-{value}-1", $"{argName}-{value}-2" };

        // Act
        var handler = McpCompletionHelpers.CreateDynamicCompletionHandler(completionFunc);

        // Assert
        Assert.NotNull(handler);
    }
}