// Generated by Copilot
using AIKit.Mcp;
using Microsoft.Extensions.Logging;
using ModelContextProtocol;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using Moq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Xunit;

namespace AIKit.Mcp.Tests;

public class McpElicitationHelpersTests
{
    [Fact]
    public async Task RequestFormInputAsync_ThrowsWhenElicitationNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();
        var schema = new ElicitRequestParams.RequestSchema
        {
            Properties = new Dictionary<string, ElicitRequestParams.PrimitiveSchemaDefinition>
            {
                ["Name"] = new ElicitRequestParams.StringSchema { Description = "User name" }
            }
        };

        // Act & Assert - Should throw InvalidOperationException when elicitation is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpElicitationHelpers.RequestFormInputAsync(
                mockServer.Object, "Enter your name", schema));
        Assert.Contains("Elicitation is not supported", exception.Message);
    }

    [Fact]
    public async Task RequestConfirmationAsync_ThrowsWhenElicitationNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when elicitation is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpElicitationHelpers.RequestConfirmationAsync(
                mockServer.Object, "Do you agree?"));
        Assert.Contains("Elicitation is not supported", exception.Message);
    }

    [Fact]
    public async Task RequestTextInputAsync_ThrowsWhenElicitationNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when elicitation is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpElicitationHelpers.RequestTextInputAsync(
                mockServer.Object, "Enter some text"));
        Assert.Contains("Elicitation is not supported", exception.Message);
    }

    [Fact]
    public async Task RequestUrlInteractionAsync_ThrowsWhenElicitationNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when elicitation is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpElicitationHelpers.RequestUrlInteractionAsync(
                mockServer.Object, "Visit this URL", "https://example.com"));
        Assert.Contains("Elicitation is not supported", exception.Message);
    }

    [Fact]
    public async Task RequestEmailInputAsync_ThrowsWhenElicitationNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when elicitation is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpElicitationHelpers.RequestEmailInputAsync(
                mockServer.Object, "Enter your email"));
        Assert.Contains("Elicitation is not supported", exception.Message);
    }

    [Fact]
    public async Task RequestDateInputAsync_ThrowsWhenElicitationNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when elicitation is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpElicitationHelpers.RequestDateInputAsync(
                mockServer.Object, "Select a date"));
        Assert.Contains("Elicitation is not supported", exception.Message);
    }

    [Fact]
    public async Task RequestNumberInputAsync_ThrowsWhenElicitationNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when elicitation is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpElicitationHelpers.RequestNumberInputAsync(
                mockServer.Object, "Enter a number"));
        Assert.Contains("Elicitation is not supported", exception.Message);
    }
}