// Generated by Copilot
using AIKit.Mcp;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using ModelContextProtocol;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using Moq;
using System.Text.Json;
using Xunit;

namespace AIKit.Mcp.Tests;

public class McpSamplingHelpersTests
{
    [Fact]
    public void CreateSamplingHandler_DelegatesToChatClient()
    {
        // Arrange
        var mockChatClient = new Mock<IChatClient>();

        // Act
        var handler = McpSamplingHelpers.CreateSamplingHandler(mockChatClient.Object);

        // Assert
        Assert.NotNull(handler);
    }

    [Fact]
    public async Task GenerateTextAsync_ThrowsWhenSamplingNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when sampling is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpSamplingHelpers.GenerateTextAsync(
                mockServer.Object, "Test prompt", maxTokens: 100, temperature: 0.7f));
        Assert.Contains("Sampling is not supported", exception.Message);
    }

    [Fact]
    public async Task GenerateTextAsync_ThrowsWhenSamplingNotSupported_NoTextContent()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when sampling is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpSamplingHelpers.GenerateTextAsync(
                mockServer.Object, "Test prompt"));
        Assert.Contains("Sampling is not supported", exception.Message);
    }

    [Fact]
    public async Task GenerateChatResponseAsync_ThrowsWhenSamplingNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();
        var messages = new[]
        {
            new ChatMessage(ChatRole.System, "You are helpful"),
            new ChatMessage(ChatRole.User, "Hello")
        };

        // Act & Assert - Should throw InvalidOperationException when sampling is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpSamplingHelpers.GenerateChatResponseAsync(
                mockServer.Object, messages, maxTokens: 100, temperature: 0.7f));
        Assert.Contains("Sampling is not supported", exception.Message);
    }

    [Fact]
    public async Task GenerateTextAsTaskAsync_ThrowsWhenSamplingNotSupported()
    {
        // Arrange
        var mockServer = new Mock<McpServer>();

        // Act & Assert - Should throw InvalidOperationException when sampling is not enabled
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => McpSamplingHelpers.GenerateTextAsTaskAsync(
                mockServer.Object, "Test prompt", maxTokens: 100, temperature: 0.7f));
        Assert.Contains("Sampling is not supported", exception.Message);
    }
}