// Generated by Copilot
using ModelContextProtocol.Server;

namespace AIKit.Mcp;

/// <summary>
/// Helper methods for working with MCP Tasks in AIKit.Mcp.
/// </summary>
public static class McpTaskHelpers
{
    /// <summary>
    /// Reports progress for a long-running operation.
    /// Note: This is a simplified implementation. Full progress support requires SDK features not available in the current version.
    /// </summary>
    /// <param name="server">The MCP server instance.</param>
    /// <param name="progressToken">Token identifying the progress operation.</param>
    /// <param name="progress">Current progress (0.0 to 1.0).</param>
    /// <param name="message">Optional progress message.</param>
    public static async Task ReportProgressAsync(
        McpServer server,
        string progressToken,
        double progress,
        string? message = null)
    {
        // Progress notifications are not fully implemented in this SDK version
        // This is a placeholder for future implementation
        await Task.CompletedTask;
    }
}

/// <summary>
/// Extension methods for McpServer to simplify common operations.
/// </summary>
public static class McpServerExtensions
{
    /// <summary>
    /// Sends a progress notification.
    /// Note: This is a simplified implementation. Full progress support requires SDK features not available in the current version.
    /// </summary>
    public static async Task NotifyProgressAsync(
        this McpServer server,
        string progressToken,
        double progress,
        string? message = null)
    {
        await McpTaskHelpers.ReportProgressAsync(server, progressToken, progress, message);
    }
}