// Generated by Copilot
using ModelContextProtocol;
using ModelContextProtocol.Server;
using ModelContextProtocol.Protocol;
using System.Text.Json.Nodes;

namespace AIKit.Mcp;

/// <summary>
/// Helper methods for working with MCP Tasks in AIKit.Mcp.
/// </summary>
public static class McpTaskHelpers
{
    /// <summary>
    /// Reports progress for a long-running operation.
    /// </summary>
    /// <param name="server">The MCP server instance.</param>
    /// <param name="progressToken">Token identifying the progress operation.</param>
    /// <param name="progress">Current progress value.</param>
    /// <param name="total">Optional total progress value.</param>
    /// <param name="message">Optional progress message.</param>
    public static Task ReportProgressAsync(
        McpServer server,
        ProgressToken progressToken,
        float progress,
        float? total = null,
        string? message = null)
    {
        var progressValue = new ProgressNotificationValue
        {
            Progress = progress,
            Total = total,
            Message = message
        };
        return server.NotifyProgressAsync(progressToken, progressValue);
    }

    /// <summary>
    /// Sends a progress notification using a ProgressNotificationValue.
    /// </summary>
    /// <param name="server">The MCP server instance.</param>
    /// <param name="progressToken">Token identifying the progress operation.</param>
    /// <param name="progress">The progress notification value.</param>
    public static Task NotifyProgressAsync(
        McpServer server,
        ProgressToken progressToken,
        ProgressNotificationValue progress)
    {
        return server.NotifyProgressAsync(progressToken, progress);
    }
}

/// <summary>
/// Extension methods for McpServer to simplify common operations.
/// </summary>
public static class McpServerExtensions
{
    /// <summary>
    /// Sends a progress notification.
    /// </summary>
    /// <param name="server">The MCP server instance.</param>
    /// <param name="progressToken">Token identifying the progress operation.</param>
    /// <param name="progress">Current progress value.</param>
    /// <param name="total">Optional total progress value.</param>
    /// <param name="message">Optional progress message.</param>
    public static Task NotifyProgressAsync(
        this McpServer server,
        ProgressToken progressToken,
        float progress,
        float? total = null,
        string? message = null)
    {
        return McpTaskHelpers.ReportProgressAsync(server, progressToken, progress, total, message);
    }
}
